testing generation of respec

diff --git a/.github/workflows/transform_with_model2owl.yml b/.github/workflows/transform_with_model2owl.yml
--- a/.github/workflows/transform_with_model2owl.yml
+++ b/.github/workflows/transform_with_model2owl.yml
@@ -17,7 +17,7 @@ jobs:
 
       - name: get model2owl
         run: |
-          git clone --branch develop-updated-deps https://github.com/OP-TED/model2owl.git
+          git clone --branch develop https://github.com/OP-TED/model2owl.git 
           pwd
 
       - name: get-saxon
@@ -65,116 +65,33 @@ jobs:
           done
         shell: bash
 
-#      - name: merge implementations xmi files into one
-#        run: |
-#          AVAILABLE_IMPLEMENTATIONS=(demo_ontology demo_ontology_module)
-#          cd model2owl
-#          mkdir -p merge-xmis
-#          for implementation in "${AVAILABLE_IMPLEMENTATIONS[@]}"
-#          do
-#            cp ../implementation/$implementation/xmi_conceptual_model/*_CM.xml merge-xmis
-#          done
-#          ls merge-xmis
-#
-#          make merge-xmi FIRST_XMI_TO_BE_MERGED_FILE_PATH=merge-xmis/demo_ontology_CM.xml
-#
-#          echo "merged XMI file"
-#          ls output/combined-xmi
-#        shell: bash
-#
-#      - name: generate combined glossary from the merged xmi
-#        run: |
-#          # get a namespaces file from an arbitrary module
-#          NS_XML_FILE_PATH=$(realpath $(find . -type f -path './implementation/*/model2owl-config/namespaces.xml' | head -1))
-#          echo "NS_XML_FILE_PATH is $NS_XML_FILE_PATH"
-#          cd model2owl
-#          make generate-glossary \
-#            XMI_INPUT_FILE_PATH=output/combined-xmi/ontologies-combined.xmi \
-#            OUTPUT_GLOSSARY_PATH=../$OUTPUT_GLOSSARY_PATH \
-#            NAMESPACES_USER_XML_FILE_PATH=${NS_XML_FILE_PATH}
-
-      - name: remove unnecessary files
-        run: |
-          sudo rm -rf model2owl
-        shell: bash
-
-      - name: commit files
-        id: commit
-        run: |
-          git config --local user.email "action@github.com"
-          git config --local user.name "github-actions"
-          git pull
-          git status
-
-          git add .
-          if [ -z "$(git status --porcelain)" ]; then
-          echo "::set-output name=push::false"
-          else
-          git commit -m "Adding convention report and glossary files"
-          echo "::set-output name=push::true"
-          fi
-        shell: bash
-
-      - name: Push changes
-        if: steps.commit.outputs.push == 'true'
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: ${{ github.ref }}
-  respec:
-    needs: transform
-    runs-on: ubuntu-latest
-    env:
-      OUTPUT_GLOSSARY_PATH: glossary/
-    steps:
-      - uses: actions/checkout@master
-        with:
-          ref: ${{ github.ref }}
-
-      - name: get model2owl
-        run: |
-          git clone --branch feature/SM15-67  https://github.com/meaningfy-ws/model2owl.git
-          pwd
-
-      - name: get-saxon
-        run: pwd && cd model2owl && make get-saxon
-
-      - name: get-jinja
-        run: cd model2owl && make create-virtual-env && make get-jinja
-
-
-      - name: generate respec
+      - name: merge implementations xmi files into one
         run: |
           AVAILABLE_IMPLEMENTATIONS=(dcat_ap_lu)
+          cd model2owl
+          mkdir -p merge-xmis
           for implementation in "${AVAILABLE_IMPLEMENTATIONS[@]}"
           do
-            echo "-------------------${implementation}---------------------------------"
-            sed -i "s/test\/ePO-default-config/..\/implementation\/${implementation}\/model2owl-config/g" model2owl/config-proxy.xsl
-            cat model2owl/config-proxy.xsl
-
-
-            CM_FILE_NAME=$(echo "${implementation}_CM.xml")
-            CM_FILE_PATH=$(echo "implementation/$implementation/xmi_conceptual_model/${CM_FILE_NAME}")
-
-            OUTPUT_RESPEC_REPORT_PATH=$(echo "implementation/$implementation/respec_report/")
-            ls -la implementation/$implementation/xmi_conceptual_model/
-            echo "CM_FILE_PATH is $CM_FILE_PATH"
-
-            mkdir -p $OUTPUT_RESPEC_REPORT_PATH
-
-            rm -f $OUTPUT_RESPEC_REPORT_PATH*.html || true
-            ls -la
-            cd model2owl
-            ls -la
-
-            make respec-json XMI_INPUT_FILE_PATH=../$CM_FILE_PATH OUTPUT_FOLDER_PATH=.
-            make generate-respec RESPEC_INPUT_JSON_PATH=${implementation}_CM_respec.json RESPEC_OUTPUT_FILE_PATH=../$OUTPUT_RESPEC_REPORT_PATH${implementation}_respec.html
-
-
-            sed -i "s/..\/implementation\/${implementation}\/model2owl-config/test\/ePO-default-config/g" config-proxy.xsl
-            cd ..
+            cp ../implementation/$implementation/xmi_conceptual_model/*_CM.xml merge-xmis
           done
+          ls merge-xmis
+
+          make merge-xmi FIRST_XMI_TO_BE_MERGED_FILE_PATH=merge-xmis/demo_ontology_CM.xml
+
+          echo "merged XMI file"
+          ls output/combined-xmi
         shell: bash
+
+      - name: generate combined glossary from the merged xmi
+        run: |
+          # get a namespaces file from an arbitrary module
+          NS_XML_FILE_PATH=$(realpath $(find . -type f -path './implementation/*/model2owl-config/namespaces.xml' | head -1))
+          echo "NS_XML_FILE_PATH is $NS_XML_FILE_PATH"
+          cd model2owl
+          make generate-glossary \
+            XMI_INPUT_FILE_PATH=output/combined-xmi/ontologies-combined.xmi \
+            OUTPUT_GLOSSARY_PATH=../$OUTPUT_GLOSSARY_PATH \
+            NAMESPACES_USER_XML_FILE_PATH=${NS_XML_FILE_PATH}
 
       - name: remove unnecessary files
         run: |
@@ -214,7 +131,7 @@ jobs:
 
       - name: get model2owl
         run: |
-          git clone --branch develop-updated-deps https://github.com/OP-TED/model2owl.git
+          git clone --branch develop https://github.com/OP-TED/model2owl.git 
           pwd
 
       - name: get-saxon
@@ -307,3 +224,309 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: ${{ github.ref }}
+
+  generate_jsonld_context:
+    needs: transform
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@master
+        with:
+          ref: ${{ github.ref }}
+
+      - name: get model2owl
+        run: |
+          git clone --branch develop https://github.com/OP-TED/model2owl.git 
+          pwd
+
+      - name: get-saxon
+        run: pwd && cd model2owl && make get-saxon
+
+      - name: get-rdflib
+        run: cd model2owl && make create-virtual-env && make get-rdflib
+
+      - name: generate JSON-LD context
+        run: |
+          AVAILABLE_IMPLEMENTATIONS=(dcat_ap_lu)
+          for implementation in "${AVAILABLE_IMPLEMENTATIONS[@]}"
+          do
+            echo "-------------------${implementation} JSON-LD context generation---------------------------------"
+            sed -i "s/test\/ePO-default-config/..\/implementation\/${implementation}\/model2owl-config/g" model2owl/config-proxy.xsl
+            cat model2owl/config-proxy.xsl
+
+            CM_FILE_NAME=$(echo "${implementation}_CM.xml")
+            CM_FILE_PATH=$(echo "implementation/$implementation/xmi_conceptual_model/${CM_FILE_NAME}")
+            NS_XML_FILE_PATH="../implementation/${implementation}/model2owl-config/namespaces.xml"
+            OUTPUT_PATH_JSONLD=$(echo "implementation/$implementation/jsonld_context/")
+
+            ls -la implementation/$implementation/xmi_conceptual_model/
+            echo "CM_FILE_PATH is $CM_FILE_PATH"
+            echo "NS_XML_FILE_PATH is $NS_XML_FILE_PATH"
+            echo "OUTPUT_PATH_JSONLD is $OUTPUT_PATH_JSONLD"
+
+            mkdir -p $OUTPUT_PATH_JSONLD
+            cd model2owl
+            ls -la
+            echo "+++++++++++++++++prepare namespaces for JSON-LD context++++++++++++++++++++++++++++"
+            # Generate enriched namespaces first (required for JSON-LD context generation)
+            make gen-enriched-ns-file \
+              NAMESPACES_USER_XML_FILE_PATH=${NS_XML_FILE_PATH}
+            echo "+++++++++++++++++generate JSON-LD context++++++++++++++++++++++++++++"
+            make generate-jsonld-context \
+              XMI_INPUT_FILE_PATH=../$CM_FILE_PATH \
+              OUTPUT_FOLDER_PATH=../$OUTPUT_PATH_JSONLD \
+              NAMESPACES_USER_XML_FILE_PATH=${NS_XML_FILE_PATH}
+            echo "-------------------end JSON-LD context generation---------------------------------"
+
+            sed -i "s/..\/implementation\/${implementation}\/model2owl-config/test\/ePO-default-config/g" config-proxy.xsl
+            cd ..
+          done
+        shell: bash
+
+      - name: remove unnecessary files
+        run: |
+          sudo rm -rf model2owl
+        shell: bash
+
+      - name: commit files
+        id: commit
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "github-actions"
+          git pull
+          git status
+
+          git add .
+          if [ -z "$(git status --porcelain)" ]; then
+          echo "::set-output name=push::false"
+          else
+          git commit -m "Adding JSON-LD context files"
+          echo "::set-output name=push::true"
+          fi
+        shell: bash
+
+      - name: Push changes
+        if: steps.commit.outputs.push == 'true'
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: ${{ github.ref }}
+
+  generate_respec:
+    needs: generate_jsonld_context
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@master
+        with:
+          ref: ${{ github.ref }}
+
+      - name: get model2owl
+        run: |
+          git clone --branch develop https://github.com/OP-TED/model2owl.git 
+          pwd
+
+      - name: get-saxon
+        run: pwd && cd model2owl && make get-saxon
+
+      - name: get-rdflib
+        run: cd model2owl && make create-virtual-env && make get-rdflib
+
+      - name: get-jinja
+        run: cd model2owl && make get-jinja
+
+      - name: get-jq
+        run: cd model2owl && make get-jq
+
+      - name: generate ReSpec documentation
+        run: |
+          AVAILABLE_IMPLEMENTATIONS=(dcat_ap_lu)
+          for implementation in "${AVAILABLE_IMPLEMENTATIONS[@]}"
+          do
+            echo "-------------------${implementation} ReSpec generation---------------------------------"
+            sed -i "s/test\/ePO-default-config/..\/implementation\/${implementation}\/model2owl-config/g" model2owl/config-proxy.xsl
+            cat model2owl/config-proxy.xsl
+
+            CM_FILE_NAME=$(echo "${implementation}_CM.xml")
+            CM_FILE_PATH=$(echo "implementation/$implementation/xmi_conceptual_model/${CM_FILE_NAME}")
+            NS_XML_FILE_PATH="../implementation/${implementation}/model2owl-config/namespaces.xml"
+            OUTPUT_PATH_RESPEC=$(echo "implementation/$implementation/respec/")
+            RESPEC_ASSETS_PATH="../implementation/${implementation}/respec_resources/assets"
+            MODULE_DIR=$(realpath "implementation/${implementation}")
+            METADATA_JSON_PATH="$MODULE_DIR/model2owl-config/metadata.json"
+
+            ls -la implementation/$implementation/xmi_conceptual_model/
+            echo "CM_FILE_PATH is $CM_FILE_PATH"
+            echo "NS_XML_FILE_PATH is $NS_XML_FILE_PATH"
+            echo "OUTPUT_PATH_RESPEC is $OUTPUT_PATH_RESPEC"
+
+            # Update all relative paths in metadata.json so that they are absolute paths
+            ALTERED_METADATA_JSON_PATH=$(mktemp --suffix=".json")
+            cp $METADATA_JSON_PATH $ALTERED_METADATA_JSON_PATH
+            jq --arg moduleDir "$MODULE_DIR" '
+              .metadata.projectLocalResources |= map(
+                .path = ($moduleDir + "/" + .path)
+              )
+            ' $METADATA_JSON_PATH > $ALTERED_METADATA_JSON_PATH
+
+            mkdir -p $OUTPUT_PATH_RESPEC
+            cd model2owl
+            ls -la
+            echo "+++++++++++++++++prepare namespaces for ReSpec generation++++++++++++++++++++++++++++"
+            # Generate enriched namespaces first (required for ReSpec generation)
+            make gen-enriched-ns-file \
+              NAMESPACES_USER_XML_FILE_PATH=${NS_XML_FILE_PATH}
+            echo "+++++++++++++++++generate ReSpec JSON data++++++++++++++++++++++++++++"
+            # First generate the ReSpec JSON data file
+            make respec-json \
+              XMI_INPUT_FILE_PATH=../$CM_FILE_PATH \
+              OUTPUT_FOLDER_PATH=../$OUTPUT_PATH_RESPEC \
+              NAMESPACES_USER_XML_FILE_PATH=${NS_XML_FILE_PATH}
+            
+            echo "+++++++++++++++++prepare ReSpec resources++++++++++++++++++++++++++++"
+            # Step 1: Copy base templates and js from Model2OWL (if they exist)
+            if [ -d "respec-resources/templates" ]; then
+              echo "Using Model2OWL base templates (appendix.j2, base.j2)"
+              # Keep Model2OWL's appendix.j2 and base.j2 if they exist
+            else
+              echo "No Model2OWL templates found, creating directory"
+              mkdir -p respec-resources/templates
+            fi
+            
+            # Step 2: Copy all custom templates from repository (except base.j2)
+            echo "Copying all custom templates from repository..."
+            if [ -d "../implementation/${implementation}/respec_resources/templates" ]; then
+              for template_file in "../implementation/${implementation}/respec_resources/templates"/*.j2; do
+                if [ -f "$template_file" ]; then
+                  template_name=$(basename "$template_file")
+                  if [ "$template_name" != "base.j2" ]; then
+                    echo "Copying template: $template_name"
+                    cp -f "$template_file" "respec-resources/templates/"
+                  else
+                    echo "Skipping base.j2 (keeping Model2OWL version)"
+                  fi
+                fi
+              done
+            else
+              echo "No custom templates directory found"
+            fi
+            
+            # Step 5: Override assets completely with your version
+            echo "Overriding assets with repository version..."
+            rm -rf respec-resources/assets
+            cp -rf "../implementation/${implementation}/respec_resources/assets" respec-resources/
+            
+            echo "ReSpec resources prepared - using  templates and assets"
+            
+            echo "+++++++++++++++++generate ReSpec documentation++++++++++++++++++++++++++++"
+            # First generate the complete ReSpec documentation
+            make generate-respec \
+              XMI_INPUT_FILE_PATH=../$CM_FILE_PATH \
+              RESPEC_OUTPUT_DIR=../$OUTPUT_PATH_RESPEC \
+              OUTPUT_FOLDER_PATH=../$OUTPUT_PATH_RESPEC \
+              RESPEC_INPUT_ASSETS_DIR=${RESPEC_ASSETS_PATH} \
+              RESPEC_DATA_JSON_PATH=../$OUTPUT_PATH_RESPEC/${implementation}_CM_respec.json \
+              RESPEC_METADATA_JSON_PATH=${ALTERED_METADATA_JSON_PATH} \
+              NAMESPACES_USER_XML_FILE_PATH=${NS_XML_FILE_PATH}
+            
+            echo "+++++++++++++++++override JS files after ReSpec generation++++++++++++++++++++++++++++"
+            # Override js folder with custom version AFTER ReSpec generation to prevent Model2OWL from overwriting
+            if [ -d "../implementation/${implementation}/respec_resources/js" ]; then
+              echo "Overriding js folder with repository version (post-generation)..."
+              rm -rf ../$OUTPUT_PATH_RESPEC/js
+              cp -rf "../implementation/${implementation}/respec_resources/js" ../$OUTPUT_PATH_RESPEC/
+            else
+              echo "Using Model2OWL's default js folder and scripts"
+            fi
+            
+            echo "+++++++++++++++++copy SHACL shapes to assets++++++++++++++++++++++++++++"
+            # Copy SHACL shapes to assets/shacl directory for validation 
+            mkdir -p ../$OUTPUT_PATH_RESPEC/assets/shacl
+            # Copy main ontology SHACL shapes 
+            cp -f ../implementation/$implementation/shacl_shapes/${implementation}_CM_shapes.ttl ../$OUTPUT_PATH_RESPEC/assets/shacl/ontology_shapes.ttl
+            # Copy JSON-LD context shapes (if exists in respec_resources)
+            if [ -f "../implementation/$implementation/respec_resources/assets/shacl/context_shapes.jsonld" ]; then
+              cp -f "../implementation/$implementation/respec_resources/assets/shacl/context_shapes.jsonld" ../$OUTPUT_PATH_RESPEC/assets/shacl/
+            fi
+            echo "SHACL shapes copied to assets/shacl directory"
+            
+            echo "-------------------end ReSpec generation---------------------------------"
+
+            sed -i "s/..\/implementation\/${implementation}\/model2owl-config/test\/ePO-default-config/g" config-proxy.xsl
+            cd ..
+          done
+        shell: bash
+
+      - name: remove unnecessary files
+        run: |
+          sudo rm -rf model2owl
+        shell: bash
+
+      - name: commit files
+        id: commit
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "github-actions"
+          git pull
+          git status
+
+          git add .
+          if [ -z "$(git status --porcelain)" ]; then
+          echo "::set-output name=push::false"
+          else
+          git commit -m "Adding ReSpec documentation files"
+          echo "::set-output name=push::true"
+          fi
+        shell: bash
+
+      - name: Push changes
+        if: steps.commit.outputs.push == 'true'
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: ${{ github.ref }}
+
+  build_pages:
+    needs: generate_respec
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.ref }}
+
+      - name: Setup Pages
+        uses: actions/configure-pages@v4
+
+      - name: Prepare ReSpec documentation for Pages
+        run: |
+          # Single implementation - copy directly to _site root
+          IMPLEMENTATION="dcat_ap_lu"
+          
+          # Create a temporary directory for Pages content
+          mkdir -p _site
+          
+          # Copy ReSpec documentation directly to _site root
+          if [ -d "implementation/$IMPLEMENTATION/respec" ]; then
+            echo "Found ReSpec documentation for $IMPLEMENTATION, copying to _site root..."
+            cp -r "implementation/$IMPLEMENTATION/respec/"* "_site/"
+            echo "Successfully copied documentation to GitHub Pages site"
+          else
+            echo "ERROR: No ReSpec documentation found for $IMPLEMENTATION"
+            exit 1
+          fi
+          
+          echo "Site structure:"
+          find _site -type f -name "*.html" | head -10
+
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v3
+
+  deploy_pages:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build_pages
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v4
